root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/taskflow-api ./cmd/server"
bin = "./tmp/taskflow-api"
include_ext = ["go", "sql"]
exclude_dir = ["tmp", "vendor"]
delay = 300
stop_on_error = true

[log]
time = true
